version: '2'

services:
  memotest:
    user: "${UID}:${GID}"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/sqlite/database.sqlite
    volumes:
      - './backend:/var/www'
      - './backend/database/sqlite:/var/www/database/sqlite'
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './backend:/var/www'
    depends_on:
      - memotest
  frontend:
    image: node:18
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    command: ["npm", "run", "dev"]
    depends_on:
      - memotest
